# Generated by Django 5.0.1 on 2025-11-04 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("campaign_project", models.CharField(max_length=255)),
                (
                    "message_channel",
                    models.CharField(
                        choices=[("email", "Email"), ("whatsapp", "WhatsApp")],
                        default="email",
                        max_length=20,
                    ),
                ),
                ("sales_offer", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CRMLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "project_enquired",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "budget_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("unit_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "lead_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_conversation_date", models.DateField(blank=True, null=True)),
                ("last_conversation_summary", models.TextField(blank=True, null=True)),
                ("family_size", models.CharField(blank=True, max_length=50, null=True)),
                ("purchase_motive", models.TextField(blank=True, null=True)),
                (
                    "financing_preference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "location_preference",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "CRM Lead",
                "verbose_name_plural": "CRM Leads",
                "ordering": ["-last_conversation_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_sent", models.BooleanField(default=False)),
                ("message_sent_at", models.DateTimeField(blank=True, null=True)),
                ("responded", models.BooleanField(default=False)),
                ("goal_achieved", models.BooleanField(default=False)),
                ("goal_achieved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_leads",
                        to="api.campaign",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="api.crmlead",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("campaign", "lead")},
            },
        ),
        migrations.CreateModel(
            name="CampaignMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("outbound", "Outbound (System to Lead)"),
                            ("inbound", "Inbound (Lead to System)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("is_ai_generated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign_lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="api.campaignlead",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("property_visit", "Property Visit"),
                            ("sales_call", "Sales Call"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateTimeField()),
                ("sales_associate_email", models.EmailField(max_length=254)),
                ("notified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign_lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_visits",
                        to="api.campaignlead",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_date"],
            },
        ),
    ]
